version: '2.1'
orbs:
  node: circleci/node@4.4.0
jobs:
  test:
    docker:
      - image: 'cimg/node:10.24.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run linter
      - run:
          command: yarn test
          name: Run tests
workflows:
  test_lib:
    jobs:
      - test
